### ISSUE TITLE
Adjusting label layout

### ISSUE THREAD

**Issue by phete67** [Finomnis/ResistorLabels#1]
Hi,

I'm trying to modify your code to work with Avery L7157 labels.

These are A4 sheets with 11x3 (33) labels 64.0mm x 24.3mm

I'm stuck trying to work out where you set the actual label height. It's always 1 inch.

Thanks for helping.
Pete

**Comment by Finomnis** [comment]
I don't think it's too easy to modify that script because I didn't really design it with adjustability in mind.
The '1 inch height' is in line 21.
But changing that will most likely break everything else alignment-related.

What you would have to change is:

- The `StickerRect` `__init__` function (lines 18-22). This one defines the boundaries of one sticker.
- The `draw_resistor_sticker` function (lines 307-361). This one defines the layout of one sticker, e.g. where to draw which text and which image on the sticker.
- The `render_stickers` call in `main` (lines 390-401), as the L7157 probably doesn't have the same number of stickers as the original 5260

Have fun and feel free to ask further questions :)

**Comment by phete67** [comment]
Yes, line 21 does really mess things up lol.I'll have a go at lines 307-361 tomorrow. I think this is where the changes will need to be made, now you have explained why line 21 messes everything up.Interestingly, adding an extra row of resistor values actually works without changing any of your code.Thanks for your quick reply. I'll let you know how I go.On 18 Jun 2021 20:48, Martin Stumpf ***@***.***> wrote:
I don't think it's too easy to modify that script because I didn't really design it with adjustability in mind.
The '1 inch height' is in line 21.
But changing that will most likely break everything else alignment-related.
What you would have to change is:
The StickerRect __init__ function (lines 18-22). This one defines the boundaries of one sticker.The draw_resistor_sticker function (lines 307-361). This one defines the layout of one sticker, e.g. where to draw which text and which image on the sticker.The render_stickers call in main (lines 390-401), as the L7157 probably doesn't have the same number of stickers as the original 5260
Have fun and feel free to ask further questions :)

**Comment by Finomnis** [comment]
After a little research, it seems that the L7157 has almost the same sticker size as the 5260, so it didn't actually require any changes in the draw_resistor_sticker function.
I added a `config` value to the `main()` function with which you can switch between the two papers.
Let me know if the numbers I entered for L7157 work, as I don't have L7157 paper here to test it.

**Comment by phete67** [comment]
It works perfectly :-)

I use Ubuntu - the name of the font "Arial Bold" is Arial_Bold.ttf
That's all I had to change, maybe add a note in the README?

Thank you for the speedy update.

**Comment by Finomnis** [comment]
Fixed in https://github.com/Finomnis/ResistorLabels/commit/9e892e8488c2c5950fb4753f7c2f5a8bbc04ade5

**Comment by Finomnis** [comment]
Is it ok if I close this issue? Unless you have further questions, of course.

**Comment by phete67** [comment]
Please close it. You have done excellent work 
Thanks
