### ISSUE TITLE
[Idea] Support dual sided sticker

### ISSUE THREAD

**Issue by spuder** [Finomnis/ResistorLabels#11]
As a user I would like to follow the pattern of [Zach Poff](https://www.zachpoff.com/resources/quick-easy-and-cheap-resistor-storage/) and fold the sticker over the edge of the bag

![](https://www.zachpoff.com/site/wp-content/uploads/resistor-box-flipping-600px.jpg)

## Idea
It would be nice if there were an option to mirror the output so it could be displayed on both sides of the bag. Here is an example: 

<img width="421" alt="Screen Shot 2022-11-06 at 9 31 28 AM" src="https://user-images.githubusercontent.com/242382/200182949-5c0e80a5-8cb0-4ad8-be7b-679b7cf5fdd4.png">

### Constraints

Understandably not all users may want this feature, so it would be ideal to make a feature flag or environment variable to enable it.

**Comment by Finomnis** [comment]
Agree :)

I feel like this is getting out of hand for a simple Python Script, I am seriously considering to rewrite the entire thing in Rust, with a proper command line and yaml configuration.

That would have the advantage that you can simply download the released binary instead of having to clone the repository and deal with git. I hear that for many people downloading things from github isn't intuitive at all; I simply don't see this point of view because I work with git/github/gitlab/gerrit etc since >10 years, so it feels very intuitive to me :D

What's your opinion on that matter?

**Comment by Finomnis** [comment]
> As a user I would like to follow the pattern of [Zach Poff](https://www.zachpoff.com/resources/quick-easy-and-cheap-resistor-storage/) and fold the sticker over the edge of the bag

I think the intend of Zach Poff was to have it only on one side, as seen in his [original pdf](https://www.zachpoff.com/site/wp-content/uploads/Resistor-Color-Code-Labels-table-Avery-5260.pdf).

I agree with your request to make it configurable, though.

**Comment by spuder** [comment]
I've created a rough draft which accomplishes what I'm hoping for here: https://github.com/Finomnis/ResistorLabels/pull/12

I've left it as a 'draft' PR because it still has 1 major bug I haven't been able to solve yet. As long as the user is printing _full_ pages, my branch works as intended.

**Comment by spuder** [comment]
Closed by https://github.com/Finomnis/ResistorLabels/pull/12
