### ISSUE TITLE
Mirror option broken 

### ISSUE THREAD

**Issue by spuder** [Finomnis/ResistorLabels#21]
Pull request #12 introduced the ability to make 2 sided stickers with `python3 LabelGenerator.py --mirror`

That functionality broke with #16 and now all generated labels are single sided. 

It _seems_ that the intent was to remove the `--mirror` option and replace it with a very obscure internal variable `    draw_both_sides:` on line 553 https://github.com/Finomnis/ResistorLabels/pull/16/files#diff-bff332ece4991cee856597e7b65a2c11c7847dec95ec96cd7bfc2810d3f0b220R553

However changing that value from False to True does not work, the PDF is still generating single sided images.

**Comment by Finomnis** [comment]
I've made the decision to change it because I personally found `mirror` quite obscure, as it isn't a mirror operation - it's a rotation. Nothing is getting mirrored. Further, I don't like the usage of global variables, I'd rather have it be passed around as an argument, so that each function is self-contained.

Further, while I am a big fan of CLI parsers, I didn't like the fact that that one is configurable through command line, while everything else is configurable in `main`. I do understand that this is partially against what other programs usually do - but adding CLI parsing would only be done cleanly if another dependency would have been introduced, and I wanted to keep the dependencies to an absolute minimum.

I do agree that it is slightly too obscure, and we should maybe instead add a section in `main` with a comment that explains it.

`It *seems* that the intent was to remove the `--mirror` option  and replace it with a very obscure internal variable` - it doesn't seem like it, that was the exact intend and that is also what was done and tested. I understand it that it is always frustrating if design decisions you found good get viewed different by other people, so I'm trying to make you understand my thought process here. I hope we can have a civilized design decision discussion here if you disagree.

Again, I am in the process of rewriting this tool into a purely CLI/yaml controlled program with pre-compiled executables for all big operating systems, however, I don't know when this is going to be finished. I want to keep this here as simple to understand as possible.

**Comment by spuder** [comment]
After more testing I figured out that `draw_both_sides` appears twice. Only the instance on line 630 that needs to be changed.

```python
    render_stickers(c, layout, resistor_values, draw_outlines=False, draw_both_sides=False)
```

```python
    render_stickers(c, layout, resistor_values, draw_outlines=False, draw_both_sides=True)
```

**Comment by Finomnis** [comment]
@spuder You are right. My bad. I forgot to remove the default arguments of the function.

Does #22 clean up your complaints sufficiently?

**Comment by spuder** [comment]
That is great, thank you.
